version: "3.8"

networks:
  diversity-lunch:

services:
  frontend:
    image: ghcr.io/brockhaus-ag/frontend-image-dev:latest
    env_file:
      - ./diversity-lunch-fe/public/config/fe.env
      - ./diversity-lunch-fe/.env
    container_name: "diversity-lunch-frontend"
    ports:
      - "4000:4000"
    environment:
      BACKEND_HOST: "diversity-lunch-backend:8080"
    depends_on:
      - backend
    networks:
      - diversity-lunch

  db:
    image: postgres
    container_name: diversity-lunch-db
    env_file:
      - ./diversity-lunch-be/docker/.env
    ports:
      - "5432:5432"
    networks:
      - diversity-lunch

  backend:
    build:
      context: ./diversity-lunch-be
    container_name: diversity-lunch-backend
    depends_on:
      - db
      - mailhog
    env_file:
      - ./diversity-lunch-be/docker/.env
    ports:
      - "8080:8080"
    networks:
      - diversity-lunch

  mailhog:
    image: mailhog/mailhog
    container_name: diversity-lunch-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - diversity-lunch
