#!/bin/sh

file_path=/usr/share/nginx/html/config/app-config.js

echo "window.appConfig = {
  REACT_APP_OIDC_CLIENT_ID: $REACT_APP_OIDC_CLIENT_ID,
  REACT_APP_OIDC_SCOPE: $REACT_APP_OIDC_SCOPE,
  REACT_APP_OIDC_CONFIG_ENDPOINT: $REACT_APP_OIDC_CONFIG_ENDPOINT,
  REACT_APP_OIDC_REDIRECT_URI: $REACT_APP_OIDC_REDIRECT_URI,
  REACT_APP_OIDC_AUTHORIZATION_ENDPOINT: $REACT_APP_OIDC_AUTHORIZATION_ENDPOINT,
};" > $file_path