package de.brockhausag.diversitylunchspringboot.dimensions.repositories;

import de.brockhausag.diversitylunchspringboot.dimensions.entities.model.BasicDimensionSelectableOption;

public interface BasicDimensionSelectableOptionRepository extends SelectableOptionsRepository<BasicDimensionSelectableOption> {

}
