package de.brockhausag.diversitylunchspringboot.dimensions.repositories;

import de.brockhausag.diversitylunchspringboot.dimensions.entities.model.MultiselectDimensionSelectableOption;

public interface MultiselectDimensionSelectableOptionRepository extends SelectableOptionsRepository<MultiselectDimensionSelectableOption> {
}
