package de.brockhausag.diversitylunchspringboot.dimensions.repositories;

import de.brockhausag.diversitylunchspringboot.dimensions.entities.model.MultiselectDimension;
import de.brockhausag.diversitylunchspringboot.dimensions.entities.model.MultiselectDimensionSelectableOption;

public interface MultiselectDimensionRepository extends DimensionRepository<MultiselectDimension, MultiselectDimensionSelectableOption> {
}
