package de.brockhausag.diversitylunchspringboot.dimensions.repositories;

import de.brockhausag.diversitylunchspringboot.dimensions.entities.model.WeightedDimension;
import de.brockhausag.diversitylunchspringboot.dimensions.entities.model.WeightedDimensionSelectableOption;

public interface WeightedDimensionRepository extends DimensionRepository<WeightedDimension, WeightedDimensionSelectableOption> {
}
