package de.brockhausag.diversitylunchspringboot.dimensions.repositories;

import de.brockhausag.diversitylunchspringboot.dimensions.entities.model.WeightedDimensionSelectableOption;

public interface WeightedDimensionSelectableOptionRepository extends SelectableOptionsRepository<WeightedDimensionSelectableOption> {
}
