apiVersion: v1

kind: Service

metadata:
  name: frontend-service
  namespace: diversitylunch
  labels:
    app: frontend

spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: ClusterIP
