openapi: 3.0.3
info:
  title: DiversityLunch new API
  version: 3.0.0
externalDocs:
  description: DiversityLunch GitHub
  url: https://github.com/BROCKHAUS-AG/DiversityLunch
servers:
  - url: http://localhost:8080/api/
tags:
  - name: BasicDimension
  - name: WeightedDimension
  - name: MultiselectDimension
  - name: Profile
paths:
  /basicdimension/all:
    get:
      tags:
        - BasicDimension
      summary: Get all basic dimensions.
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BasicDimension'
        '401':
          description: unauthorized
        '500':
          description: internal server error
  /weighteddimension/all:
    get:
      tags:
        - WeightedDimension
      summary: Get all weighted dimensions.
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeightedDimension'
        '401':
          description: unauthorized
        '500':
          description: internal server error
  /multiselectdimension/all:
    get:
      tags:
        - MultiselectDimension
      summary: Get all multiselect dimensions.
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MultiselectDimension'
        '401':
          description: unauthorized
        '500':
          description: internal server error
  /profile:
    get:
      tags:
        - Profile
      summary: Get profile of logged in user.
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '400':
          description: profile does not exist
        '401':
          description: unauthorized
        '500':
          description: internal server error
    put:
      tags:
        - Profile
      summary: Update profile of logged in user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
      responses:
        '200':
          description: saved changes
        '401':
          description: unauthorized
        '500':
          description: internal server error
    post:
      tags:
        - Profile
      summary: Create profile for logged in user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
      responses:
        '200':
          description: profile created
        '401':
          description: unauthorized
        '500':
          description: internal server error
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Projekt
        profile_question:
          type: string
          example: In welchem Projekt arbeitest du derzeit?
    BasicDimensionSelectableOption:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: EON
        ignore_in_scoring:
          type: boolean
          example: true
    BasicDimension:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        category:
          $ref: '#/components/schemas/Category'
        selectable_options:
          type: array
          items: 
            $ref: '#/components/schemas/BasicDimensionSelectableOption'
        default_value:
          $ref: '#/components/schemas/BasicDimensionSelectableOption'
    WeightedDimensionSelectableOption:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: 2000
        ignore_in_scoring:
          type: boolean
          example: true
        weight:
          type: integer
          format: int32
          example: 2
    WeightedDimension:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        category:
          $ref: '#/components/schemas/Category'
        selectable_options:
          type: array
          items: 
            $ref: '#/components/schemas/WeightedDimensionSelectableOption'
        default_value:
          $ref: '#/components/schemas/WeightedDimensionSelectableOption'
    MultiselectDimensionSelectableOption:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: 2000
    MultiselectDimension:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        category:
          $ref: '#/components/schemas/Category'
        selectable_options:
          type: array
          items: 
            $ref: '#/components/schemas/MultiselectDimensionSelectableOption'
    Profile:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Max Mustermann
        email:
          type: string
          example: max.mustermann@mustermail.com
        birthyear:
          type: integer
          format: int64
          example: 2000
        was_changed_by_admin:
          type: boolean
          example: true
        selectedbasicoptions:
          type: array
          items:
            $ref: '#/components/schemas/SelectedBasicOption'
        selectedweightedoptions:
          type: array
          items:
            $ref: '#/components/schemas/SelectedWeightedOption'
        selectedmultiselectoptions:
          type: array
          items:
            $ref: '#/components/schemas/SelectedMultiselectOption'
    SelectedBasicOption:
      type: object
      properties:
        selected:
          $ref: '#/components/schemas/BasicDimensionSelectableOption'
        category:
          $ref: '#/components/schemas/Category'
    SelectedWeightedOption:
      type: object
      properties:
        selected:
          $ref: '#/components/schemas/WeightedDimensionSelectableOption'
        category:
          $ref: '#/components/schemas/Category'
    SelectedMultiselectOption:
      type: object
      properties:
        selected:
          type: array
          items:
            $ref: '#/components/schemas/MultiselectDimensionSelectableOption'
        category:
          $ref: '#/components/schemas/Category'