version: "3.8"

services:
  frontend:
    image: ghcr.io/brockhaus-ag/frontend-image-dev:latest
    container_name: "diversity-lunch-frontend"
    ports:
      - "4000:4000"
    environment:
      BACKEND_HOST: "http://localhost:8080"