DELETE FROM account_entity;
DELETE FROM meeting_proposal_entity;
DELETE FROM meeting_entity;
DELETE FROM profile_entity;
DELETE FROM country_entity;
DELETE FROM diet_entity;
DELETE FROM education_entity;
DELETE FROM gender_entity;
DELETE FROM hobby_entity;
DELETE FROM hobby_category_entity;
DELETE FROM language_entity;
DELETE FROM project_entity;
DELETE FROM religion_entity;
DELETE FROM sexual_orientation_entity;
DELETE FROM work_experience_entity;
DELETE FROM sexual_orientation_entity;
DELETE FROM social_background_entity;
DELETE FROM social_background_discrimination_entity;

