INSERT INTO country_entity(descriptor) VALUES ('Algerien'),('Andorra'),('Angola'),('Antiguaundbarbuda'),('Argentinien'),('Armenien'),('Aserbaidschan'),('Australien'),('Bahamas'),('Bahrain'),('Bangladesch'),('Barbados'),('Belgien'),('Belize'),('Benin'),('Bhutan'),('Bolivien'),('Botswana'),('Botwana'),('Brasilien'),('Brunei'),('Bulgarien'),('Burkinafaso'),('Burundi'),('Chile'),('Chinarepubliktaiwan'),('Costarica'),('Deutschland'),('Dominica'),('Dominikanischerepublik'),('Dschibuti'),('Danemark'),('Ecuador'),('Elsalvador'),('Elfenbeinkuste'),('Eritrea'),('Estland'),('Eswatini'),('Finnland'),('Frankreich'),('Faroer'),('Gabun'),('Gambia'),('Georgien'),('Ghana'),('Ginea'),('Gineabissau'),('Grenada'),('Griechenland'),('Gronland'),('Guatemala'),('Guyana'),('Haiti'),('Honduras'),('Hongkong'),('Indien'),('Indonesien'),('Irak'),('Iran'),('Irland'),('Island'),('Israel'),('Italien'),('Jamaika'),('Japan'),('Jemen'),('Jordanien'),('Kambodscha'),('Kamerun'),('Kanada'),('Kapverde'),('Katar'),('Kenia'),('Kirgisistan'),('Kiribati'),('Kolumbien'),('Komoren'),('Kongo'),('Kosovo'),('Kroatien'),('Kuba'),('Kuwait'),('Laos'),('Lesotho'),('Lettland'),('Libanon'),('Liberia'),('Libyen'),('Liechtenstein'),('Litauen'),('Luxemburg'),('Macau'),('Madagaskar'),('Malawi'),('Malaysia'),('Malediven'),('Mali'),('Malta'),('Marokko'),('Mauretanien'),('Mauritius'),('Mexiko'),('Moldawien'),('Monaco'),('Mongolei'),('Mosambik'),('Motenegro'),('Myanmar'),('Namibia'),('Nepal'),('Neuseeland'),('Nicaragua'),('Niederlande'),('Niger'),('Nigeria'),('Nordkorea'),('Nordmazedonien'),('Norwegen'),('Oman'),('Pakistan'),('Palastina'),('Panama'),('Papuaneuguinea'),('Paraguay'),('Peru'),('Philippinen'),('Polen'),('Portugal'),('Republikmoldau'),('Ruanda'),('Rumanien'),('Russland'),('Sambia'),('Saudiarabien'),('Schweden'),('Schweiz'),('Senegal'),('Serbien'),('Seychellen'),('Sierraleone'),('Simbabwe'),('Singapur'),('Slowakei'),('Slowenien'),('Somalia'),('Spanien'),('Srilanka'),('Stkittsundnevis'),('Stlucia'),('Stvincentunddiegrenadinen'),('Sudan'),('Suriname'),('Syrien'),('Saotomeundprincipe'),('Sudafrika'),('Sudkorea'),('Sudsudan'),('Tadschikistan'),('Taiwan'),('Tansania'),('Thailand'),('Timorleste'),('Togo'),('Tonga'),('Trinidadundtobago'),('Tschad'),('Tschechien'),('Tunesien'),('Turkmenistan'),('Tuvalu'),('Turkei'),('Usa'),('Uganda'),('Ukraine'),('Ungarn'),('Uruguay'),('Usbekistan'),('Vatikanstadt'),('Venezuela'),('Vereinigtearabischeemirate'),('Vereinigteskonigreich'),('Vietnam'),('Volksrepublikchina'),('Wallisundfutuna'),('Weissrussland'),('Westsahara'),('Zentralafrikanischerepublik'),('Zypern'),('Agypten'),('Aquatorialguinea'),('Athiopien'),('Osterreich'),('Albanien'),('Bosnienundherzegowina'),('Kasachstan'),('Sanmarino');
INSERT INTO diet_entity(descriptor)  VALUES ('Fleischesser'),('Vegetarier'),('Veganer'), ('Sonstige');
INSERT INTO education_entity(descriptor) VALUES ('Ausbildung'), ('Studium'), ('Andere Wege');
INSERT INTO gender_entity(descriptor) VALUES ('Männlich'), ('Weiblich'), ('Keine Angabe');
INSERT INTO language_entity(descriptor) VALUES ('Akan'),('Amharisch'),('Arabisch'),('Aserbaidschanisch'),('Assamesisch'),('Awadhi'),('Belutschisch'),('Bengalisch'),('Bhojpuri'),('Bulgarisch'),('Burmesisch'),('Cebuano'),('Chhattisgarhi'),('Chichewa'),('Chittagonisch'),('Dakhini'),('Deutsch'),('Dhundari'),('Daenisch'),('Englisch'),('Estnisch'),('Finnisch'),('Franzoesisch'),('Fulfulde'),('Ganchinesisch'),('Griechisch'),('Guarani'),('Gujarati'),('Haitanischeskreol'),('Hakkachinesisch'),('Haryanvi'),('Hausa'),('Hiligaynon'),('Hindi'),('Hmong'),('Hocharabisch'),('Igbo'),('Ilokano'),('Indonesisch'),('Irisch'),('Italienisch'),('Japanisch'),('Javanisch'),('Jinchinesisch'),('Kannada'),('Kantonesisch'),('Kasachisch'),('Katalanisch'),('Khmer'),('Kinyarwanda'),('Kirundi'),('Konkani'),('Koreanisch'),('Kroatisch'),('Kurdisch'),('Lettisch'),('Litauisch'),('Maduresisch'),('Magahi'),('Maithili'),('Malagasy'),('Malaiisch'),('Malayalam'),('Maltesisch'),('Marathi'),('Marwari'),('Minanchinesisch'),('Minbeichinesisch'),('Mindongchinesisch'),('Moore'),('Nahuatl'),('Nepali'),('Niederlaendisch'),('Oriya'),('Oromo'),('Panjabi'),('Paschtunisch'),('Persisch'),('Polnisch'),('Portugiesisch'),('Quechua'),('Rumaenisch'),('Russisch'),('Saraiki'),('Schwedisch'),('Sindhi'),('Singhalesisch'),('Slowakisch'),('Slowenisch'),('Somali'),('Spanisch'),('Suaheli'),('Sundanesisch'),('Sylheti'),('Tagalog'),('Tamil'),('Telugu'),('Thai'),('Tschechisch'),('Turkmenisch'),('Tuerkisch'),('Uigurisch'),('Ukrainisch'),('Ungarisch'),('Urdu'),('Usbekisch'),('Vietnamesisch'),('Weissrussisch'),('Wuchinesisch'),('Xiangchinesisch'),('Yoruba'),('Zhuangchinesisch'),('Isixhosa'),('Isizulu'),('Aegyptischarabisch'),('Mandarinchinesisch');
INSERT INTO project_entity(descriptor) VALUES ('Externes Projekt'), ('Internes Projekt');
INSERT INTO religion_entity(descriptor) VALUES ('Judentum'),('Christentum'),('Islam'),('Hinduismus'),('Buddhismus'),('Sonstige'),('Kein Glaube');
INSERT INTO work_experience_entity(descriptor, weight) VALUES ('0-3 Jahre', 1), ('4-10 Jahre', 2),('über 10 Jahre', 3);
INSERT INTO hobby_entity(descriptor) VALUES ('Angeln'), ('Ballsport'), ('Bogenschießen'), ('Camping'), ('Dart'), ('DIY'), ('Filme'), ('Gaming'), ('Gärtnern'), ('Fotografie'), ('Gesellschaftsspiele'), ('Jagen'), ('Joggen'), ('Kampfsport'), ('Klettern'), ('Kochen'), ('Lesen'), ('Malen'), ('Musik'), ('Puzzlen'), ('Radsport'), ('Tanzen'), ('Theater'), ('Wandern'), ('Yoga'), ('Sonstiges');
INSERT INTO sexual_orientation_entity(descriptor) VALUES
                                                      ('Heterosexuell'),
                                                      ('Homosexuell'),
                                                      ('Bisexuell'),
                                                      ('Asexuell'),
                                                      ('Pansexuell'),
                                                      ('weitere Orientierungen'),
                                                      ('keine Angabe');
INSERT INTO social_background_entity(descriptor) VALUES ('Akademikerfamilie'), ('Nichtakademisches Elternhaus'), ('keine Angabe');
INSERT INTO social_background_discrimination_entity(descriptor) VALUES ('Ja'), ('Nein'), ('keine Angabe');
