apiVersion: v1

kind: Service

metadata:
  name: backend-service
  namespace: {{ .Values.namespace }}
  labels:
    app: backend

spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
