
{{- $namespace := .Values.namespace }}

  {{- range .Values.ingressController}}
    {{- if not (hasKey .ingress.metadata.annotations "kubernetes.io/ingress.class") }}
      {{ $_ := set .ingress.metadata.annotations "kubernetes.io/ingress.class" "nginx" }}
    {{- end}}


      {{- $newHost := list (dict "host" "localhost")}}

    {{- range .ingress.rules}}
      {{- if not (hasKey . "host") }}
        {{$_ := set . "host" "localhost"}}
     {{- end }}
    {{- end}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .ingress.metadata.name }}
  namespace: {{ $namespace }}
  {{- with .ingress.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .ingress.tls }}
  tls:
    {{- range  .ingress.tls }}
    - hosts:
         {{- range .hosts}}
        {{. | quote}}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .ingress.rules}}
    - host: {{.host}}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8080
          - path: /swagger-ui
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8080
          - path: /v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
  {{- end }}
    {{- end}}