apiVersion: v1
kind: Service
metadata:
  name: postgres-headless-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    app: postgres