name: Test-Parsing-Version-Number

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  parse-version-number:
    runs-on: ubuntu-latest
    steps:
    - id: parse_version_number
      run: |
        echo "parsing message '${{ github.event.pull_request.title }}'..."
        VERSION_NUMBER=`echo "${{ github.event.pull_request.title }}" | grep -o -E "[0-9]+\.[0-9]+\.[0-9]+" | head -n 1`
        echo found $VERSION_NUMBER
        echo "version_no=$VERSION_NUMBER" >> $GITHUB_OUTPUT
    - name: Verify Version Number
      if: ${{ steps.parse_version_number.outputs.version_no == '' }}
      run: |
        echo No Version-Number found, exiting...
        exit 1
