name: Build Docker-Image

on:
  push:
    branches: [main,development]
  workflow_dispatch:
jobs:
  frontend-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Npm Setup
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Npm Install
        run: npm install
        working-directory: ./diversity-lunch-fe
      - name: Build Frontend
        run: npm run build-fe
        working-directory: ./diversity-lunch-fe
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./diversity-lunch-fe
          file: ./diversity-lunch-fe/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/brockhaus-ag/frontend-image:latest

  backend-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17.0.2
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.2
      - name: Add execution privileges
        run: chmod +x ./mvnw
        working-directory: ./diversity-lunch-be
      - name: Build Backend
        run: ./mvnw package
        working-directory: ./diversity-lunch-be
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./diversity-lunch-be
          file: ./diversity-lunch-be/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/brockhaus-ag/backend-image:latest
