name: Build Docker-Prod-Images

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  parse-version-number:
    runs-on: ubuntu-latest
    outputs:
      version-no: ${{ steps.parse_version_number.outputs.version_no }}
    steps:
    - id: parse_version_number
      run: |
        echo "parsing message '${{ github.event.head_commit.message }}'..."
        VERSION_NUMBER=`echo "${{ github.event.head_commit.message }}" | grep -o -E "[0-9]+\.[0-9]+\.[0-9]+" | head 1`
        echo found $VERSION_NUMBER
        echo "version_no=$VERSION_NUMBER" >> $GITHUB_OUTPUT

  build-backend-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17.0.2
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.2
      - name: Add execution privileges
        run: chmod +x ./mvnw
        working-directory: ./diversity-lunch-be
      - name: Build Backend
        run: ./mvnw package
        working-directory: ./diversity-lunch-be
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./diversity-lunch-be
          file: ./diversity-lunch-be/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/brockhaus-ag/backend-image:latest
            ghcr.io/brockhaus-ag/backend-image:${{needs.parse-version-number.outputs.version-no}}

  build-frontend-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./diversity-lunch-fe
          file: ./diversity-lunch-fe/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/brockhaus-ag/frontend-image:latest
            ghcr.io/brockhaus-ag/frontend-image:${{needs.parse-version-number.outputs.version-no}}

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC2iOxEBVA4KodlcdKXgJQpwxAZwur4TRUDrpo2nY3PMzV3va6oC7JOlHVFFR+4hgyUC/Pe5FtmcFNHePS08qvhrOziaHgdm5hahOINbHQ0rW/ED+6toFREDQPiLflCzcOUC0LyKtyK0wMBHKqcZMa22gK9/oT0Lsi+TY4mpCjlrGocpcA3Q4Y92m56wgKNDtMsGylqjGQYN9pMsRvw/7I1CFikDxdxdKtIt5I1QJQbYeyTF9ncneGu1lIejYElZcpVGtEO9FCYnGwWcODcVIzpjtcgIBYu/+jX5gP1x3rXS+HCt7Mg2L6F1/JEShgYVnvr+vsr28mckpJPRuN8NaV+VgHMN13MhEd7r97gS/zlOXrmAvH5rYhxHRo+UUzhYZQl49Otz96YGzCifBDSwUP7szAVphg840GvtYt0+YWAbgMJWqB0trtNiPqUN6yo0AUEJHOYWKm6F+nRDCbKTuRNHYIU020jnegwKNw5Ukt32n3mDddaBr6gLsS6gX1w76ldcbepeiF/W8Z5HQ/qc5utKR4BLVINjdgx5/wK5ju80ywqjokB7J35NORWNOlOMPoUvjQq8mOXAOb2OnrSySbGHATzuwxgPhXwc/pkHst7ciOEUcNEzL/YP02ufnUhmlqvzt7vEXUmHj5kzf96a6zYqwXP0ZIuYFiId0ZHPV27xw==