name: Build and Test

on:
  push:
    branches: [ feat/17753-testing-pipeline]
  pull_request:
    branches: [ development, main ]
  workflow_dispatch:

jobs:

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17.0.2
        uses: actions/setup-java@v3
        with:
          java-version: 17.0.2
          distribution: corretto
      - name: Pull mailhog image
        run: docker pull mailhog/mailhog:latest
      - name: Build container
        run: docker run --publish 8025:8025 --publish 1025:1025 -d mailhog/mailhog
      - name: Add execution privileges
        run: chmod +x ./mvnw
        working-directory: ./diversity-lunch-be
      - name: Unit Test and Integration Test Backend
        run: ./mvnw verify -P failsafe
        working-directory: ./diversity-lunch-be

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17.0.2
        uses: actions/setup-java@v3
        with:
          java-version: 17.0.2
          distribution: corretto
      - name: Add execution privileges
        run: chmod +x ./mvnw
        working-directory: ./diversity-lunch-be
      - name: Build Backend .jar
        run: ./mvnw package
        working-directory: ./diversity-lunch-be


  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Npm Setup
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Npm Install
        run: npm install
        working-directory: ./diversity-lunch-fe
      - name: Test frontend
        run: npm test
        working-directory: ./diversity-lunch-fe

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Npm Setup
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Npm Install
        run: npm install
        working-directory: ./diversity-lunch-fe
      - name: Build Frontend
        run: npm run build
        working-directory: ./diversity-lunch-fe

  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Npm Setup
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Npm Install
        run: npm install
        working-directory: ./diversity-lunch-fe
      - name: Test frontend
        run: npm run lint
        working-directory: ./diversity-lunch-fe

  notify:
    runs-on: ubuntu-latest
    if: always()
    needs: [test-backend, build-backend, test-frontend, build-frontend, lint-frontend]
    steps:
      - uses: actions/checkout@v3
      - name: Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
