name: Build Docker-Dev-Images

on:
  push:
    branches: [development]
  workflow_dispatch:

jobs:
  parse-version-number:
    runs-on: ubuntu-latest
    outputs:
      version-no: ${{ steps.parse_version_number.outputs.version_no }}
    steps:
    - id: parse_version_number
      run: |
        echo parsing ${{ github.event.head_commit.message }}...
        VERSION_NUMBER=`echo "${{ github.event.head_commit.message }}" | grep -o -E "[0-9]+\.[0-9]+\.[0-9]+"`
        echo found $VERSION_NUMBER
        echo echo "version_no=$VERSION_NUMBER" >> $GITHUB_OUTPUT

  build-backend-image-dev:
    runs-on: ubuntu-latest
    needs: parse-version-number
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17.0.2
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.2
      - name: Add execution privileges
        run: chmod +x ./mvnw
        working-directory: ./diversity-lunch-be
      - name: Build Backend
        run: ./mvnw package
        working-directory: ./diversity-lunch-be
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./diversity-lunch-be
          file: ./diversity-lunch-be/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/brockhaus-ag/backend-image-dev:latest
            ghcr.io/brockhaus-ag/backend-image-dev:${{needs.parse-version-number.outputs.version-no}}

  build-frontend-image-dev:
    runs-on: ubuntu-latest
    needs: parse-version-number
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./diversity-lunch-fe
          file: ./diversity-lunch-fe/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/brockhaus-ag/frontend-image-dev:latest
            ghcr.io/brockhaus-ag/frontend-image-dev:${{needs.parse-version-number.outputs.version-no}}
