name: Test-Workflow

on:
  workflow_dispatch:
  push:
    branches: [ feat/17753-testing-pipeline ]

jobs:
  get-deployments:
    runs-on: ubuntu-latest
    outputs:
      frontend_deployment: ${{ steps.get-deployments.outputs.frontend }}
      backend_deployment: ${{ steps.get-deployments.outputs.backend }}
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: ssh.dev.azure.com
          private-key: ${{ secrets.AZURE_PRIVATE_KEY }}

      - name: Clone repository
        run: git clone git@ssh.dev.azure.com:v3/brockhaus-ag/Diversity-Lunch/Kubernetes

      - name: Get Deployments
        id: get-deployments
        run: |
          BACKEND=`cat Kubernetes/azure_dev/backend.yaml`
          FRONTEND=`cat Kubernetes/azure_dev/frontend.yaml`
          echo "backend=$BACKEND" >> $GITHUB_OUTPUT
          echo "frontend=$FRONTEND" >> $GITHUB_OUTPUT

      - name: Delete Repository
        run: rm -rf Kubernetes

  debug-deployments:
    runs-on: ubuntu-latest
    needs: get-deployments
    steps:
      - name: backend-debug
        run: echo ${{needs.get-deployments.outputs.backend_deployment}}
      - name: frontend-debug
        run: echo ${{needs.get-deployments.outputs.backend_deployment}}
