name: Test-Workflow

on:
    workflow_dispatch:
    push:
      branches: [ feat/17753-testing-pipeline ]

jobs:
    clone-repository:
        runs-on: ubuntu-latest
        steps:
          - name: Setup SSH
            uses: MrSquaare/ssh-setup-action@v1
            with:
              host: ssh.dev.azure.com
              private-key: ${{ secrets.AZURE_PRIVATE_KEY }}

          - name: Clone repository
            run: git clone git@ssh.dev.azure.com:v3/brockhaus-ag/Diversity-Lunch/Kubernetes

          - name: Debug
            run: cat Kubernetes/README.md
