name: Test-Workflow

on:
  workflow_dispatch:
  push:
    branches: [ feat/17753-testing-pipeline ]

jobs:
  get-deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: ssh.dev.azure.com
          private-key: ${{ secrets.AZURE_PRIVATE_KEY }}

      - name: Clone repository
        run: git clone git@ssh.dev.azure.com:v3/brockhaus-ag/Diversity-Lunch/Kubernetes

      - name: Upload Backend-Deployment
        uses: actions/upload-artifact@master
        with:
          name: backend_deployment
          path: Kubernetes/azure_dev/backend.yaml

      - name: Upload Frontend-Deployment
        uses: actions/upload-artifact@master
        with:
          name: frontend_deployment
          path: Kubernetes/azure_dev/frontend.yaml

      - name: Delete Repository
        run: rm -rf Kubernetes

  modify-deployments:
    runs-on: ubuntu-latest
    needs: get-deployments
    steps:
      - name: Download Fronend-Deployment
        uses: actions/download-artifact@master
        with:
          name: backend_deployment

      - name: Download Backend-Deployment
        uses: actions/download-artifact@master
        with:
          name: frontend_deployment

      - name: Set Container Version Tag
        run: |
          VERSION_NO=1.1.1
          sed -i -- "s%__VERSION_NUMBER__%$VERSION_NO%g" frontend.yaml backend.yaml

      - name: backend-debug
        run: cat backend.yaml
      - name: frontend-debug
        run: cat frontend.yaml

  azure-shit:
    runs-on: ubuntu-latest
    needs: modify-deployments
    environment: development
    steps:
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.resource_group }}'
          cluster-name: '${{ secrets.cluster_name }}'
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: Test Kubectl
        run: kubectl config current-context
